server:
  port: 8761  # 当前 Eureka Server 的服务端口
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false   # 是否要注册自己
    fetch-registry: false  # 是否获取其他 Eureka Server 服务的数据
    service-url:
       defaultZone: http://localhost:8761/eureka/  # 注册中心的访问地址